services:
  - type: web
    name: chatgpt-telegram-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: TELEGRAM_TOKEN
        value: YOUR_TELEGRAM_BOT_TOKEN
      - key: OPENAI_API_KEY
        value: YOUR_OPENAI_API_KEY
